const std = @import("std");

const Basic = struct {
    is_number: bool = false,
    is_Atom: bool=false,
    is_Symbol:bool=false,
    is_symbol:bool=false,
    is_Indexed :bool = false,
    is_Dummy:bool = false,
    is_Wild:bool = false,
    is_Function:bool = false,
    is_Add:bool = false,
    is_Mul:bool = false,
    is_Pow:bool = false,
    is_Number:bool = false,
    is_Float:bool = false,
    is_Rational:bool = false,
    is_Integer:bool = false,
    is_NumberSymbol:bool = false,
    is_Order:bool = false,
    is_Derivative:bool = false,
    is_Piecewise:bool = false,
    is_Poly:bool = false,
    is_AlgebraicNumber:bool = false,
    is_Relational:bool = false,
    is_Equality:bool = false,
    is_Boolean:bool = false,
    is_Not:bool = false,
    is_Matrix:bool = false,
    is_Vector:bool = false,
    is_Point:bool = false,
    is_MatAdd:bool = false,
    is_MatMul:bool = false,
    is_real: ?bool,ded_real: ?bool,
    is_zero: ?bool,
    is_negative: ?bool,
    is_commutative: ?bool,

    // kind: Kind = UndefinedKind
};
